# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 721)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_all = QtWidgets.QGridLayout()
        self.gridLayout_all.setObjectName("gridLayout_all")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_picture = QtWidgets.QHBoxLayout()
        self.horizontalLayout_picture.setObjectName("horizontalLayout_picture")
        self.comboBox_picture = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_picture.setObjectName("comboBox_picture")
        self.comboBox_picture.addItem("")
        self.comboBox_picture.addItem("")
        self.horizontalLayout_picture.addWidget(self.comboBox_picture)
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_id.setSizePolicy(sizePolicy)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout_picture.addWidget(self.lineEdit_id)
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_picture.addWidget(self.pushButton_ok)
        self.horizontalLayout.addLayout(self.horizontalLayout_picture)
        self.gridLayout_all.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_picture = QtWidgets.QGridLayout()
        self.gridLayout_picture.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_picture.setObjectName("gridLayout_picture")
        self.label_picture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_picture.sizePolicy().hasHeightForWidth())
        self.label_picture.setSizePolicy(sizePolicy)
        self.label_picture.setObjectName("label_picture")
        self.gridLayout_picture.addWidget(self.label_picture, 0, 0, 1, 1)
        self.gridLayout_all.addLayout(self.gridLayout_picture, 0, 0, 1, 1)
        self.gridLayout_info = QtWidgets.QGridLayout()
        self.gridLayout_info.setObjectName("gridLayout_info")
        self.tableWidget_painter_info = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_painter_info.sizePolicy().hasHeightForWidth())
        self.tableWidget_painter_info.setSizePolicy(sizePolicy)
        self.tableWidget_painter_info.setColumnCount(1)
        self.tableWidget_painter_info.setObjectName("tableWidget_painter_info")
        self.tableWidget_painter_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_painter_info.setHorizontalHeaderItem(0, item)
        self.tableWidget_painter_info.horizontalHeader().setVisible(False)
        self.tableWidget_painter_info.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_painter_info.verticalHeader().setVisible(True)
        self.gridLayout_info.addWidget(self.tableWidget_painter_info, 9, 0, 1, 2)
        self.listWidget_painter = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_painter.sizePolicy().hasHeightForWidth())
        self.listWidget_painter.setSizePolicy(sizePolicy)
        self.listWidget_painter.setObjectName("listWidget_painter")
        self.gridLayout_info.addWidget(self.listWidget_painter, 1, 1, 5, 1)
        self.listWidget_user_info = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_user_info.sizePolicy().hasHeightForWidth())
        self.listWidget_user_info.setSizePolicy(sizePolicy)
        self.listWidget_user_info.setObjectName("listWidget_user_info")
        self.gridLayout_info.addWidget(self.listWidget_user_info, 6, 1, 1, 1)
        self.tableWidget_picture_info = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_picture_info.sizePolicy().hasHeightForWidth())
        self.tableWidget_picture_info.setSizePolicy(sizePolicy)
        self.tableWidget_picture_info.setToolTip("")
        self.tableWidget_picture_info.setObjectName("tableWidget_picture_info")
        self.tableWidget_picture_info.setColumnCount(1)
        self.tableWidget_picture_info.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_picture_info.setItem(3, 0, item)
        self.tableWidget_picture_info.horizontalHeader().setVisible(False)
        self.tableWidget_picture_info.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_picture_info.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_picture_info.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_picture_info.verticalHeader().setStretchLastSection(False)
        self.gridLayout_info.addWidget(self.tableWidget_picture_info, 6, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_tag = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tag.sizePolicy().hasHeightForWidth())
        self.lineEdit_tag.setSizePolicy(sizePolicy)
        self.lineEdit_tag.setObjectName("lineEdit_tag")
        self.gridLayout.addWidget(self.lineEdit_tag, 1, 1, 1, 1)
        self.lineEdit_comment = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_comment.sizePolicy().hasHeightForWidth())
        self.lineEdit_comment.setSizePolicy(sizePolicy)
        self.lineEdit_comment.setObjectName("lineEdit_comment")
        self.gridLayout.addWidget(self.lineEdit_comment, 0, 1, 1, 1)
        self.label_comment = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_comment.sizePolicy().hasHeightForWidth())
        self.label_comment.setSizePolicy(sizePolicy)
        self.label_comment.setObjectName("label_comment")
        self.gridLayout.addWidget(self.label_comment, 0, 0, 1, 1)
        self.horizontalLayout_bookmark_button = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bookmark_button.setObjectName("horizontalLayout_bookmark_button")
        self.pushButton_add_bookmark = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_bookmark.setObjectName("pushButton_add_bookmark")
        self.horizontalLayout_bookmark_button.addWidget(self.pushButton_add_bookmark)
        self.pushButton_delete_bookmark = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_bookmark.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete_bookmark.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_bookmark.setSizePolicy(sizePolicy)
        self.pushButton_delete_bookmark.setObjectName("pushButton_delete_bookmark")
        self.horizontalLayout_bookmark_button.addWidget(self.pushButton_delete_bookmark)
        self.gridLayout.addLayout(self.horizontalLayout_bookmark_button, 2, 0, 1, 2)
        self.label_tag = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tag.sizePolicy().hasHeightForWidth())
        self.label_tag.setSizePolicy(sizePolicy)
        self.label_tag.setObjectName("label_tag")
        self.gridLayout.addWidget(self.label_tag, 1, 0, 1, 1)
        self.gridLayout_info.addLayout(self.gridLayout, 8, 0, 1, 2)
        self.listWidget_picture = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_picture.sizePolicy().hasHeightForWidth())
        self.listWidget_picture.setSizePolicy(sizePolicy)
        self.listWidget_picture.setObjectName("listWidget_picture")
        self.gridLayout_info.addWidget(self.listWidget_picture, 1, 0, 5, 1)
        self.gridLayout_all.addLayout(self.gridLayout_info, 0, 1, 3, 1)
        self.gridLayout_5.addLayout(self.gridLayout_all, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuGG = QtWidgets.QMenu(self.menubar)
        self.menuGG.setObjectName("menuGG")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfuck = QtWidgets.QAction(MainWindow)
        self.actionfuck.setObjectName("actionfuck")
        self.menuGG.addAction(self.actionfuck)
        self.menubar.addAction(self.menuGG.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PixivSpider_GUI"))
        self.comboBox_picture.setItemText(0, _translate("MainWindow", "图片ID"))
        self.comboBox_picture.setItemText(1, _translate("MainWindow", "画师ID"))
        self.pushButton_ok.setText(_translate("MainWindow", "下载"))
        self.label_picture.setText(_translate("MainWindow", "TextLabel"))
        item = self.tableWidget_painter_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "item"))
        item = self.tableWidget_picture_info.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "图片ID"))
        item = self.tableWidget_picture_info.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "图片标题"))
        item = self.tableWidget_picture_info.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "图片简介"))
        item = self.tableWidget_picture_info.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "已加入书签"))
        item = self.tableWidget_picture_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "value"))
        __sortingEnabled = self.tableWidget_picture_info.isSortingEnabled()
        self.tableWidget_picture_info.setSortingEnabled(False)
        self.tableWidget_picture_info.setSortingEnabled(__sortingEnabled)
        self.lineEdit_tag.setText(_translate("MainWindow", "该项可为空"))
        self.lineEdit_comment.setText(_translate("MainWindow", "该项可为空"))
        self.label_comment.setText(_translate("MainWindow", "备注"))
        self.pushButton_add_bookmark.setText(_translate("MainWindow", "加入书签"))
        self.pushButton_delete_bookmark.setText(_translate("MainWindow", "删除书签"))
        self.label_tag.setText(_translate("MainWindow", "标签"))
        self.menuGG.setTitle(_translate("MainWindow", "GG"))
        self.actionfuck.setText(_translate("MainWindow", "fuck"))
